version: '3'

services:
  posy-resto:
    container_name: posy-resto-admin-panel
    image: posy-resto-admin-panel
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.local
    ports:
      - '3300:3000'
