export const subscriptionHistoryMenuLabel = 'Subscription History'
export const subscriptionPlanMenuLabel = 'Subscription Plan'
export const outletMenuLabel = 'Outlet List'
export const foodCategoryLabel = 'Food Category'
export const deliveryTransactionMenuLabel = 'Delivery Transaction'
